FROM alpine:edge

RUN apk add --no-cache \
        cmake ninja clang git pkgconfig \
        qt6-qtbase-dev \
        qt6-qttools-dev \
        qt6-qtsvg-dev \
        qt6-qtdeclarative-dev \
        qt6-qtwebengine-dev \
        qt6-qtscxml-dev \
        qt6-qtnetworkauth-dev \
        boost-dev \
        libx11-dev \
        libxkbfile-dev \
        libxcomposite-dev \
        libxrender-dev \
        libxdamage-dev \
        libxcb-dev \
        xcb-util-renderutil-dev \
        libxscrnsaver-dev \
        libtorrent-rasterbar-dev \
        libmaxminddb-dev \
        qxmpp-dev \
        qca-qt6-dev \
        libotr-dev \
        pidgin-dev \
        toxcore-dev \
        hunspell-dev \
        taglib-dev \
        gstreamer-dev \
        chromaprint-dev \
        ffmpeg-dev \
        libmtp-dev \
        poppler-qt5-dev \
        djvulibre-dev \
        quazip-dev \
        tidyhtml-dev \
        libidn-dev \
        libqrencode-dev \
        lm-sensors-dev \
        eudev-dev \
        libnl3-dev \
        utf8proc-dev \
        qscintilla-dev \
        qtermwidget-dev \
    && rm -rf /var/cache/apk/*