name:                tstools
version:             0.1.0.0
github:              "0xd34df00d/tstools"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2020 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/tstools#readme>

dependencies:
- base >= 4.7 && < 5
- file-embed
- foldl
- interpolate
- optparse-generic
- text
- turtle

executables:
  tstools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
