/**********************************************************************
 * LeechCraft - modular cross-platform feature rich internet client.
 * Copyright (C) 2006-2014  Georg Rudoy
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/

#include "msgeditautocompleter.h"
#include <QTextEdit>
#include "core.h"
#include "util.h"
#include "xmlsettingsmanager.h"

namespace LeechCraft
{
namespace Azoth
{
	MsgEditAutocompleter::MsgEditAutocompleter (const QString& entryId,
			QTextEdit *edit, QObject *parent)
	: QObject { parent }
	, EntryId_ { entryId }
	, MsgEdit_ { edit }
	{
	}

	struct NickReplacement
	{
		int Length_;
		QString NewText_;
	};

	NickReplacement MsgEditAutocompleter::GetNickFromState (const QStringList& participants, const QString& postNick)
	{
		if (AvailableNickList_.isEmpty ())
		{
			for (const auto& item : participants)
				if (item.startsWith (NickFirstPart_, Qt::CaseInsensitive))
					AvailableNickList_ << item + postNick;

			if (AvailableNickList_.isEmpty ())
				return {};

			return { NickFirstPart_.size (), AvailableNickList_ [CurrentNickIndex_] };
		}
		else
		{
			QStringList newAvailableNick;

			for (const auto& item : participants)
				if (item.startsWith (NickFirstPart_, Qt::CaseInsensitive))
					newAvailableNick << item + postNick;

			int lastNickLen = -1;
			if ((newAvailableNick != AvailableNickList_) && (!newAvailableNick.isEmpty ()))
			{
				int newIndex = newAvailableNick.indexOf (AvailableNickList_ [CurrentNickIndex_ - 1]);
				lastNickLen = AvailableNickList_ [CurrentNickIndex_ - 1].length ();

				while (newIndex == -1 && CurrentNickIndex_ > 0)
					newIndex = newAvailableNick.indexOf (AvailableNickList_ [--CurrentNickIndex_]);

				CurrentNickIndex_ = (newIndex == -1 ? 0 : newIndex);
				AvailableNickList_ = newAvailableNick;
			}

			if (CurrentNickIndex_ < AvailableNickList_.count () && CurrentNickIndex_)
				return { AvailableNickList_ [CurrentNickIndex_ - 1].size (), AvailableNickList_ [CurrentNickIndex_] };
			else if (CurrentNickIndex_)
			{
				CurrentNickIndex_ = 0;
				return { AvailableNickList_.last ().size (), AvailableNickList_ [CurrentNickIndex_] };
			}
			else
				return { lastNickLen, AvailableNickList_ [CurrentNickIndex_] };
		}
	}

	void MsgEditAutocompleter::complete ()
	{
		const auto entryObj = Core::Instance ().GetEntry (EntryId_);
		const auto entry = qobject_cast<IMUCEntry*> (entryObj);
		if (!entry)
			return;

		auto currentMUCParticipants = GetMucParticipants (EntryId_);
		currentMUCParticipants.removeAll (entry->GetNick ());
		if (currentMUCParticipants.isEmpty ())
			return;

		auto cursor = MsgEdit_->textCursor ();

		int cursorPosition = cursor.position ();
		int pos = -1;

		auto text = MsgEdit_->toPlainText ();

		if (AvailableNickList_.isEmpty ())
		{
			pos = text.lastIndexOf (' ', cursorPosition ? cursorPosition - 1 : 0);
			LastSpacePosition_ = pos;
		}
		else
			pos = LastSpacePosition_;

		if (NickFirstPart_.isNull ())
			NickFirstPart_ = cursorPosition ?
					text.mid (pos + 1, cursorPosition - pos - 1) :
					"";

		QString postNick;
		if (pos == -1)
			postNick = XmlSettingsManager::Instance ().property ("PostAddressText").toString ();
		postNick += " ";
		const auto& replacement = GetNickFromState (currentMUCParticipants, postNick);
		if (replacement.NewText_.isEmpty ())
			return;

		text.replace (pos + 1, replacement.Length_, replacement.NewText_);
		++CurrentNickIndex_;

		MsgEdit_->setPlainText (text);
		cursor.setPosition (pos + 1 + replacement.NewText_.size ());
		MsgEdit_->setTextCursor (cursor);
	}

	void MsgEditAutocompleter::resetState ()
	{
		NickFirstPart_.clear ();
		if (!AvailableNickList_.isEmpty ())
		{
			AvailableNickList_.clear ();
			CurrentNickIndex_ = 0;
		}
	}
}
}
