.TH LEECHCRAFT "1" "Oct 2013"
.SH NAME
\fBLeechCraft\fR \- Extensible modular internet-client.
.SH SYNOPSIS
.B lc_anhero_crash_process [options]
.SH DESCRIPTION
.B LeechCraft
is an free cross-platfrom modular live environment. See
documentation for \fBleechcraft\fR for more information about
LeechCraft.
.PP
\fBlc_anhero_crashprocess\fR is the crash handler process invoked
by main LeechCraft process when it crashes. This executable isn't
meant to be run by users directly, so no options are described here.
