find_package(PkgConfig)
pkg_check_modules(TOX REQUIRED IMPORTED_TARGET toxcore)

if (TOX_INCLUDE_DIRS AND TOX_LIBRARIES)
	message (STATUS "Found Tox includes at: ${TOX_INCLUDE_DIRS}")
	message (STATUS "Found Tox libraries: ${TOX_LIBRARIES}")
	message (STATUS "Found Tox libraries at: ${TOX_LIBRARY_DIRS}")
else ()
	message (FATAL_ERROR "Could NOT find Tox")
endif ()
