/**********************************************************************
 * LeechCraft - modular cross-platform feature rich internet client.
 * Copyright (C) 2006-2013  Georg Rudoy
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/

#include "launcherdroparea.h"
#ifndef USE_QT5
#include <QGraphicsSceneDragDropEvent>
#endif
#include <QCursor>
#include <QMimeData>

namespace LeechCraft
{
namespace SB2
{
#ifdef USE_QT5
	LauncherDropArea::LauncherDropArea (QQuickItem *parent)
	: QQuickItem (parent)
#else
	LauncherDropArea::LauncherDropArea (QDeclarativeItem *parent)
	: QDeclarativeItem (parent)
#endif
	{
#ifdef USE_QT5
		setFlag (QQuickItem::ItemAcceptsDrops);
#else
		setAcceptDrops (true);
#endif
	}

	bool LauncherDropArea::GetAcceptingDrops () const
	{
#ifdef USE_QT5
		return flags () & QQuickItem::ItemAcceptsDrops;
#else
		return acceptDrops ();
#endif
	}

	void LauncherDropArea::SetAcceptingDrops (bool accepting)
	{
		if (GetAcceptingDrops () == accepting)
			return;

#ifdef USE_QT5
		setFlag (QQuickItem::ItemAcceptsDrops, accepting);
#else
		setAcceptDrops (accepting);
#endif
		emit acceptingDropsChanged (accepting);
	}

#ifdef USE_QT5
	void LauncherDropArea::dragEnterEvent (QDragEnterEvent *event)
#else
	void LauncherDropArea::dragEnterEvent (QGraphicsSceneDragDropEvent *event)
#endif
	{
		auto data = event->mimeData ();
		if (!data->formats ().contains ("x-leechcraft/tab-tabclass"))
			return;

		event->acceptProposedAction ();
		setCursor (QCursor (Qt::DragCopyCursor));
	}

#ifdef USE_QT5
	void LauncherDropArea::dragLeaveEvent (QDragLeaveEvent*)
#else
	void LauncherDropArea::dragLeaveEvent (QGraphicsSceneDragDropEvent*)
#endif
	{
		unsetCursor ();
	}

#ifdef USE_QT5
	void LauncherDropArea::dropEvent (QDropEvent *event)
#else
	void LauncherDropArea::dropEvent (QGraphicsSceneDragDropEvent *event)
#endif
	{
		unsetCursor ();
		emit tabDropped (event->mimeData ()->data ("x-leechcraft/tab-tabclass"));
	}
}
}
